name: Account Service Workflow

on:
  push:
    branches: [ main ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Setup Java
      - uses: actions/setup-java@v4
        with:
          java-version: '26'
          distribution: 'temurin'

      - name: Build project
      - run: mvn clean verify
